# improve colors
set -g default-terminal 'screen-256color'
set -g default-shell "$SHELL"
set -g default-command "reattach-to-user-namespace -l ${SHELL}"

# Setup 'v' to begin selection as in Vim
bind-key -t vi-copy v begin-selection
bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
unbind -t vi-copy Enter
bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"
