#!/usr/bin/env sh

if [[ -s "/usr/local/share/chruby/chruby.sh" ]]; then
  source "/usr/local/share/chruby/chruby.sh"
fi

if [[ -s "/usr/share/chruby/chruby.sh" ]]; then
  source "/usr/share/chruby/chruby.sh"
fi

chruby 2.7.0

if [[ -s "/usr/local/share/chruby/auto.sh" ]]; then
  source "/usr/local/share/chruby/auto.sh"
fi
