#!/usr/bin/env sh

if [[ -s "/usr/local/share/chruby/chruby.sh" ]]; then
  source "/usr/local/share/chruby/chruby.sh"
  chruby 2.5.0
fi

if [[ -s "/usr/share/chruby/chruby.sh" ]]; then
  source "/usr/share/chruby/chruby.sh"
  chruby 2.5.0
fi
