#!/usr/bin/env sh

# create and change into a directory
function md () {
  mkdir -p "$@" && cd "$@";
}

function gogofmt () {
  for f in $(git status --short | awk '{print $2}'); do
    gofmt -w $f
  done
}

# Clone repos from GitHub.
#
# Usage: clone maxjacobson/film_snob
function clone () {
  splitter_rb="puts ARGV.fetch(0).split('/')"
  splitter_first_rb="$splitter_rb.first"
  splitter_last_rb="$splitter_rb.last"

  gh_user="$(ruby -e "$splitter_first_rb" "$@")"
  gh_repo="$(ruby -e "$splitter_last_rb" "$@")"
  gh_user_dir="$HOME/src/gh/$gh_user"

  mkdir -p "$gh_user_dir" &&
    cd "$gh_user_dir" &&
    if test -d "$gh_repo"; then
      echo "Already exists..."
    else
      set -x
      gh repo clone "$@"
    fi
    cd "$gh_repo"
}
