#!/bin/sh

set -e

tempdir="$(mktemp --directory)"
cd "$tempdir"
git clone https://github.com/catppuccin/bat.git
mkdir -p ~/.config/bat/themes

for path in ./bat/themes/*.tmTheme; do
  cp "$path" ~/.config/bat/themes
done

bat cache --build
rm -rf "$tempdir"
