#!/usr/bin/env ruby

require "fileutils"
require "pathname"
require "net/http"
require "uri"

class RemoteScript < Struct.new(:local_path, :remote_url)
  def install
    if File.exist?(path)
      puts "skipping #{path}"
    else
      puts "installing #{path}"
      response = Net::HTTP.get_response(URI(remote_url))

      if response.is_a?(Net::HTTPSuccess)
        FileUtils.mkdir_p(path.parent)
        File.write(path, response.body)
      else
        puts "Failed to fetch #{remote_url} #{response.inspect}"
        exit 1
      end
    end
  end

  private

  def path
    @path ||= Pathname.new(File.expand_path(local_path))
  end
end

RemoteScript.new(
  "~/.vim/autoload/plug.vim",
  "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim",
).install
