#!/usr/bin/env ruby

require "fileutils"
require "open-uri"
require "pathname"

class RemoteScript < Struct.new(:local_path, :remote_url)
  def install
    puts "Installing #{local_path}"
    if File.exist?(path)
      puts "Skipping, it already exists (delete to update)"
    else
      response = open(remote_url)

      if response.status.include?("200")
        FileUtils.mkdir_p(path.parent)
        File.write(path, response.read)
      else
        raise response.status.inspect
      end
    end
  end

  private

  def path
    @path ||= Pathname.new(File.expand_path(local_path))
  end
end

[
  # install the zsh-specific completions
  RemoteScript.new(
    "~/.zsh/_git",
    "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh",
  ),

  # also install the bash-specific ones, because the zsh ones depend on them
  RemoteScript.new(
    "~/.zsh/git-completion.bash",
    "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash",
  ),
].each(&:install)
