#!/usr/bin/env ruby

require "fileutils"
require "open-uri"
require "pathname"

class RemoteScript < Struct.new(:local_path, :remote_url)
  def install
    if File.exist?(path)
      puts "skipping #{path}"
    else
      puts "installing #{path}"
      response = open(remote_url)

      if response.status.include?("200")
        FileUtils.mkdir_p(path.parent)
        File.write(path, response.read)
      else
        raise response.status.inspect
      end
    end
  end

  private

  def path
    @path ||= Pathname.new(File.expand_path(local_path))
  end
end

class GitRepository < Struct.new(:url, :target)
  def install
    if Dir.exist?(target_path)
      Dir.chdir(target_path) do
        system!("git pull --quiet")
      end
    else
      system!("git clone #{url} #{target}")
    end
  end

  private

  def target_path
    @target_path ||= Pathname.new(File.expand_path(target))
  end

  def system!(command)
    system(command) or raise
  end
end

[
  # install https://github.com/zsh-users/zsh-autosuggestions
  GitRepository.new(
    "https://github.com/zsh-users/zsh-autosuggestions",
    "~/.zsh/zsh-autosuggestions",
  ),

  # install the zsh-specific completions
  RemoteScript.new(
    "~/.zsh/_git",
    "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.zsh",
  ),

  # also install the bash-specific ones, because the zsh ones depend on them
  RemoteScript.new(
    "~/.zsh/git-completion.bash",
    "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash",
  ),

  RemoteScript.new(
    "~/.vim/autoload/plug.vim",
    "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim",
  ),
].each(&:install)
