#!/bin/sh

set -e

tempdir="$(mktemp --directory)"
cd "$tempdir"
git clone https://github.com/hukl/Smyck-Color-Scheme.git

mkdir -p ~/.config/nvim/colors
cp "./Smyck-Color-Scheme/smyck.vim" ~/.config/nvim/colors

mkdir -p ~/.config/bat/themes
cp "./Smyck-Color-Scheme/Smyck.tmTheme" ~/.config/bat/themes

bat cache --build
rm -rf "$tempdir"
