[user]
name = "Max Jacobson"
email = "max@hardscrabble.net"

# Use work email for repos under FAMLI directory
[[--scope]]
--when.repositories = ["~/FAMLI"]
[--scope.user]
email = "maxwell.jacobson@maryland.gov"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519"

[ui]
default-command = "log"

[template-aliases]
'format_short_signature(signature)' = 'author.name()'
