#!/bin/sh

set -euo pipefail

if /home/max/bin/runx xrandr | grep "DP-1-1" | grep " connected" >/dev/null; then
  echo "I, [$(date)] Going into desktop mode because a display is connected via mini-displayport" >> /home/max/.handle-monitor-change-event.log
  /home/max/bin/runx /home/max/bin/desktop_xrandr
elif ! /home/max/bin/runx xrandr | grep " connected" | grep -v eDP-1; then
  echo "I, [$(date)] Going into laptop-only mode because the only connected display is the embedded one" >> /home/max/.handle-monitor-change-event.log
  /home/max/bin/runx /home/max/bin/laptop_xrandr
else
  connected_displays="$(/home/max/bin/runx xrandr | grep ' connected' | awk '{print $1}' | xargs)"
  echo "I, [$(date)] Taking no automatic action because the connected displays are using ports we don't usually use ($connected_displays)" >> /home/max/.handle-monitor-change-event.log
fi
