#!/bin/sh

# setup a machine for ruby hacking

cd ~

# get rvm, which will get its requirements
\curl -L https://get.rvm.io | bash -s stable

source $HOME/.rvm/scripts/rvm

rvm requirements
rvm install ruby-2.0.0-p451
rvm use 2.0.0-p451 --default
rm ~/.zlogin
rm ~/.zshrc

mkdir ~/bin

gem install hub
hub hub standalone > ~/bin/hub && chmod +x ~/bin/hub
curl https://raw.github.com/garybernhardt/selecta/master/selecta > ~/bin/selecta && chmod +x ~/bin/selecta

hub clone maxjacobson/dotfiles
rm -rf dotfiles/.git
rm dotfiles/README.md
ruby ~/dotfiles/scripts/move_dotfiles.rb
rm -rf dotfiles

gem install bundler

cd ~
echo 'must now run: source ~/.bash_profile'
