#!/bin/sh

# setup a machine for ruby hacking

# get rvm, which will get its requirements
\curl -L https://get.rvm.io | bash -s stable
source /home/`whoami`/.rvm/scripts/rvm
rvm requirements
rvm install ruby-2.0.0-p247
rm ~/.zlogin
rm ~/.zshrc

mkdir ~/bin

gem install hub
hub hub standalone > ~/bin/hub && chmod +x ~/bin/hub

hub clone maxjacobson/dotfiles
rm -rf dotfiles/.git
rm dotfiles/README.md
rm -rf dotfiles/scripts
mv dotfiles/* .
rm -rf dotfiles

mkdir -p ~/.vim/autoload ~/.vim/bundle; \
curl -Sso ~/.vim/autoload/pathogen.vim \
    https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim

cd ~/.vim
hub clone kien/ctrlp.vim bundle/ctrlp.vim
hub clone kchmck/vim-coffee-script bundle/vim-coffee-script/
hub clone godlygeek/tabular bundle/tabular

gem install pry rspec

source ~/.bash_profile
